[versions]
coroutines = "1.7.2"
flyway = "9.20.0"
graphql = "6.5.3"
jackson = "2.15.2"
junit = "5.9.3"
kotest = "5.6.2"
kotlin = "1.9.0"
ktor = "2.3.2"
slf4j = "2.0.7"
testcontainers = "1.18.3"

[plugins]
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
graphql = { id = "com.expediagroup.graphql", version.ref = "graphql" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
openapi = { id = "org.openapi.generator", version = "6.6.0" }
spotless = { id = "com.diffplug.spotless", version = "6.19.0" }

[libraries]
# Kotlin
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }

# Kotlinx Coroutines
kotlinx-coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-jdk8 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlinx-coroutines-slf4j = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-slf4j", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

# Kotlinx Metadata
kotlinx-metadata-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-metadata-jvm", version = "0.6.2" }

# Jackson
jackson-bom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jackson" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }

# Ktor
ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor" }

# Ktor Serialization
ktor-serialization-jackson = { group = "io.ktor", name = "ktor-serialization-jackson", version.ref = "ktor" }

# Ktor Server
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-call-logging = { group = "io.ktor", name = "ktor-server-call-logging", version.ref = "ktor" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }

# Ktor Client
ktor-client-apache = { group = "io.ktor", name = "ktor-client-apache", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }

# Auth0
java-jwt = { group = "com.auth0", name = "java-jwt", version = "4.4.0" } # følger ktor-server-auth-jwt

# Caffeine
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version = "3.1.6" }

# Kafka
kafka-clients = { group = "org.apache.kafka", name = "kafka-clients", version = "3.4.0" } # følger rapids-and-rivers
rapidsAndRivers = { group = "com.github.navikt", name = "rapids-and-rivers", version = "2023062911391688031585.522193a413de" }

# JDBC
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version = "5.0.1" }
kotliquery = { group = "com.github.seratch", name = "kotliquery", version = "1.9.0" }
postgresql = { group = "org.postgresql", name = "postgresql", version = "42.6.0" }

# Redis
jedis = { group = "redis.clients", name = "jedis", version = "4.4.3" }

# Team Hjelpemidler
hm-database = { group = "no.nav.hjelpemidler", name = "hm-database", version = "0.1.2" }
hm-http = { group = "no.nav.hjelpemidler", name = "hm-http", version = "0.1.2" }

# GraphQL
graphql-kotlin-ktor-client = { group = "com.expediagroup", name = "graphql-kotlin-ktor-client", version.ref = "graphql" }
graphql-kotlin-client-jackson = { group = "com.expediagroup", name = "graphql-kotlin-client-jackson", version.ref = "graphql" }

# Metrics
influxdb-client-kotlin = { group = "com.influxdb", name = "influxdb-client-kotlin", version = "6.9.0" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version = "1.11.0" }

# Slf4j
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

# Logging
kotlin-logging = { group = "io.github.microutils", name = "kotlin-logging", version = "3.0.5" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.4.8" }
logback-syslog4j = { group = "com.papertrailapp", name = "logback-syslog4j", version = "1.0.0" }
logstash-logback-encoder = { group = "net.logstash.logback", name = "logstash-logback-encoder", version = "7.4" }

# JUnit
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }

# Kotest
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json", version.ref = "kotest" }
kotest-assertions-ktor = { group = "io.kotest.extensions", name = "kotest-assertions-ktor", version = "2.0.0" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

# MockK
mockk = { group = "io.mockk", name = "mockk-jvm", version = "1.13.5" }

# Nimbus
nimbus-jose-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version = "9.31" }

# Testcontainers
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers" }
testcontainers-kafka = { group = "org.testcontainers", name = "kafka", version.ref = "testcontainers" }
testcontainers-mockserver = { group = "org.testcontainers", name = "mockserver", version.ref = "testcontainers" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }

[bundles]
jackson = [
    "jackson-databind",
    "jackson-dataformat-yaml",
    "jackson-datatype-jsr310",
    "jackson-module-kotlin",
]
ktor-server = [
    "ktor-serialization-jackson",
    "ktor-server-auth-jwt",
    "ktor-server-call-logging",
    "ktor-server-content-negotiation",
    "ktor-server-core",
    "ktor-server-netty",
    "ktor-server-status-pages",
]
ktor-client = [
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-client-mock",
]
ktor-server-test = [
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "junit-jupiter-params",
    "kotest-assertions-core",
    "kotest-assertions-json",
    "kotest-assertions-ktor",
    "kotest-runner-junit5",
    "kotlin-test-junit5",
    "kotlinx-coroutines-test",
    "ktor-server-test-host",
    "mockk",
    "nimbus-jose-jwt",
    "testcontainers-junit",
    "testcontainers-postgresql",
]
graphql-client = [
    "graphql-kotlin-ktor-client",
    "graphql-kotlin-client-jackson",
]
metrics = [
    "influxdb-client-kotlin",
    "micrometer-registry-prometheus",
]
logging-runtime = [
    "logback-classic",
    "logstash-logback-encoder",
]
junit = [
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "junit-jupiter-params",
    "kotlin-test-junit5",
]
kotest = [
    "kotest-assertions-core",
    "kotest-assertions-json",
    "kotest-runner-junit5",
]
test = [
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "junit-jupiter-params",
    "kotest-assertions-core",
    "kotest-assertions-json",
    "kotest-runner-junit5",
    "kotlin-test-junit5",
    "kotlinx-coroutines-test",
    "mockk",
]
