[versions]
confluent = "7.6.1"
coroutines = "1.8.0"
flyway = "10.11.1"
graphql = "7.1.1"
jackson = "2.17.0"
junit = "5.10.2"
kafka = "3.7.0" # følger rapids-and-rivers
koin = "3.5.6"
kotest = "5.8.1"
kotlin = "1.9.23"
ktor = "2.3.10"
openapi = "7.5.0"
serialization = "1.6.3"
slf4j = "2.0.13"
spotless = "6.25.0"
testcontainers = "1.19.7"
tmsKtorTokenSupport = "4.1.0"

[plugins]
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
graphql = { id = "com.expediagroup.graphql", version.ref = "graphql" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
openapi = { id = "org.openapi.generator", version.ref = "openapi" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# Kotlin
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }

# Kotlinx Coroutines
kotlinx-coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-debug = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version.ref = "coroutines" }
kotlinx-coroutines-jdk8 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlinx-coroutines-reactive = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactive", version.ref = "coroutines" }
kotlinx-coroutines-slf4j = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-slf4j", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

# Reflection
classgraph = { group = "io.github.classgraph", name = "classgraph", version = "4.8.172" }
kotlinx-metadata-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-metadata-jvm", version = "0.9.0" }

# Kotlinx Serialization
kotlinx-serialization-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-bom", version.ref = "serialization" }
kotlinx-serialization-cbor = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-cbor-jvm", version.ref = "serialization" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core-jvm", version.ref = "serialization" }
kotlinx-serialization-hocon = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-hocon", version.ref = "serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "serialization" }
kotlinx-serialization-properties = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-properties-jvm", version.ref = "serialization" }

# Jackson
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-bom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jackson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-dataformat-cbor = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-cbor", version.ref = "jackson" }
jackson-dataformat-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }

# Ktor
ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor" }
ktor-gradle-plugin = { group = "io.ktor.plugin", name = "plugin", version.ref = "ktor" }

ktor-client-apache = { group = "io.ktor", name = "ktor-client-apache", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-client-resources = { group = "io.ktor", name = "ktor-client-resources", version.ref = "ktor" }

ktor-serialization-jackson = { group = "io.ktor", name = "ktor-serialization-jackson", version.ref = "ktor" }

ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth-jvm", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt-jvm", version.ref = "ktor" }
ktor-server-call-id = { group = "io.ktor", name = "ktor-server-call-id", version.ref = "ktor" }
ktor-server-call-logging = { group = "io.ktor", name = "ktor-server-call-logging", version.ref = "ktor" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-double-receive = { group = "io.ktor", name = "ktor-server-double-receive", version.ref = "ktor" }
ktor-server-metrics-micrometer = { group = "io.ktor", name = "ktor-server-metrics-micrometer", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }

# JWT
java-jwt = { group = "com.auth0", name = "java-jwt", version = "4.4.0" } # følger ktor-server-auth-jwt
nimbus-jose-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version = "9.37.3" }

# tms-ktor-token-support
azure-exchange = { group = "no.nav.tms.token.support", name = "azure-exchange", version.ref = "tmsKtorTokenSupport" }
azure-validation = { group = "no.nav.tms.token.support", name = "azure-validation", version.ref = "tmsKtorTokenSupport" }
azure-validation-mock = { group = "no.nav.tms.token.support", name = "azure-validation-mock", version.ref = "tmsKtorTokenSupport" }
idporten-sidecar = { group = "no.nav.tms.token.support", name = "idporten-sidecar", version.ref = "tmsKtorTokenSupport" }
idporten-sidecar-mock = { group = "no.nav.tms.token.support", name = "idporten-sidecar-mock", version.ref = "tmsKtorTokenSupport" }
tokendings-exchange = { group = "no.nav.tms.token.support", name = "tokendings-exchange", version.ref = "tmsKtorTokenSupport" }
tokenx-validation = { group = "no.nav.tms.token.support", name = "tokenx-validation", version.ref = "tmsKtorTokenSupport" }
tokenx-validation-mock = { group = "no.nav.tms.token.support", name = "tokenx-validation-mock", version.ref = "tmsKtorTokenSupport" }

# NoCommons
nocommons = { group = "no.bekk.bekkopen", name = "nocommons", version = "0.16.0" }

# Java Annotations
java-annotations = { group = "org.jetbrains", name = "annotations", version = "24.1.0" }

# Koin
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-core-coroutines = { group = "io.insert-koin", name = "koin-core-coroutines", version.ref = "koin" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }
koin-test-junit5 = { group = "io.insert-koin", name = "koin-test-junit5", version.ref = "koin" }

# Kafka
kafka-clients = { group = "org.apache.kafka", name = "kafka-clients", version.ref = "kafka" }
kafka-streams = { group = "org.apache.kafka", name = "kafka-streams", version.ref = "kafka" }
kafka-streams-test-utils = { group = "org.apache.kafka", name = "kafka-streams-test-utils", version.ref = "kafka" }
rapidsAndRivers = { group = "com.github.navikt", name = "rapids-and-rivers", version = "2024041714471713358051.71746f05c18e" }

# Confluent
kafka-avro-serializer = { group = "io.confluent", name = "kafka-avro-serializer", version.ref = "confluent" }
kafka-streams-avro-serde = { group = "io.confluent", name = "kafka-streams-avro-serde", version.ref = "confluent" }

# JDBC
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
h2 = { group = "com.h2database", name = "h2", version = "2.2.224" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version = "5.1.0" }
kotliquery = { group = "com.github.seratch", name = "kotliquery", version = "1.9.0" }
ojdbc11 = { group = "com.oracle.database.jdbc", name = "ojdbc11", version = "23.3.0.23.09" }
postgresql = { group = "org.postgresql", name = "postgresql", version = "42.7.3" }

# Cache
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version = "3.1.8" }
jedis = { group = "redis.clients", name = "jedis", version = "5.1.2" }
lettuce = { group = "io.lettuce", name = "lettuce-core", version = "6.3.2.RELEASE" }

# DigiHoT
hm-contract-pdl-avro = { group = "no.nav.hjelpemidler", name = "hm-contract-pdl-avro", version = "1.0.1" }
hm-database = { group = "no.nav.hjelpemidler", name = "hm-database", version = "0.2.16" }
hm-http = { group = "no.nav.hjelpemidler", name = "hm-http", version = "0.2.10" }
hm-nare = { group = "no.nav.hjelpemidler", name = "hm-nare", version = "0.2.6" }

# GraphQL
graphql-client-jackson = { group = "com.expediagroup", name = "graphql-kotlin-client-jackson", version.ref = "graphql" }
graphql-gradle-plugin = { group = "com.expediagroup", name = "graphql-kotlin-gradle-plugin", version.ref = "graphql" }
graphql-ktor-client = { group = "com.expediagroup", name = "graphql-kotlin-ktor-client", version.ref = "graphql" }

# Metrics
influxdb-client-kotlin = { group = "com.influxdb", name = "influxdb-client-kotlin", version = "7.0.0" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version = "1.12.5" }

# Slf4j
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-bom = { group = "org.slf4j", name = "slf4j-bom", version.ref = "slf4j" }
slf4j-jdk-platform-logging = { group = "org.slf4j", name = "slf4j-jdk-platform-logging", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

# Logging
kotlin-logging = { group = "io.github.microutils", name = "kotlin-logging", version = "3.0.5" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.6" }
logback-syslog4j = { group = "com.papertrailapp", name = "logback-syslog4j", version = "1.0.0" }
logstash-logback-encoder = { group = "net.logstash.logback", name = "logstash-logback-encoder", version = "7.4" }

# Spotless
spotless-gradle-plugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }

# OpenAPI
microprofile-openapi = { group = "org.eclipse.microprofile.openapi", name = "microprofile-openapi-api", version = "3.1.1" }
openapi-gradle-plugin = { group = "org.openapitools", name = "openapi-generator-gradle-plugin", version.ref = "openapi" }
swagger-annotations = { group = "io.swagger.core.v3", name = "swagger-annotations", version = "2.2.21" }

# Unleash
unleash = { group = "no.finn.unleash", name = "unleash-client-java", version = "4.4.1" }

# JUnit
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }

# Kotest
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json", version.ref = "kotest" }
kotest-assertions-ktor = { group = "io.kotest.extensions", name = "kotest-assertions-ktor", version = "2.0.0" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

# Mocking
mockk = { group = "io.mockk", name = "mockk-jvm", version = "1.13.10" }
wiremock = { group = "org.wiremock", name = "wiremock", version = "3.5.4" }

# Testcontainers
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers" }
testcontainers-kafka = { group = "org.testcontainers", name = "kafka", version.ref = "testcontainers" }
testcontainers-mockserver = { group = "org.testcontainers", name = "mockserver", version.ref = "testcontainers" }
testcontainers-oracle-free = { group = "org.testcontainers", name = "oracle-free", version.ref = "testcontainers" }
testcontainers-oracle-xe = { group = "org.testcontainers", name = "oracle-xe", version.ref = "testcontainers" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }

[bundles]
jackson = [
    "jackson-databind",
    "jackson-datatype-jsr310",
    "jackson-module-kotlin",
]
ktor-server = [
    "ktor-serialization-jackson",
    "ktor-server-auth-jwt",
    "ktor-server-call-id",
    "ktor-server-call-logging",
    "ktor-server-content-negotiation",
    "ktor-server-core",
    "ktor-server-netty",
    "ktor-server-status-pages",
]
ktor-client = [
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-client-mock",
]
ktor-server-test = [
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "junit-jupiter-params",
    "kotest-assertions-core",
    "kotest-assertions-json",
    "kotest-assertions-ktor",
    "kotest-runner-junit5",
    "kotlin-test-junit5",
    "kotlinx-coroutines-test",
    "ktor-server-test-host",
    "mockk",
    "nimbus-jose-jwt",
    "testcontainers-junit",
    "testcontainers-postgresql",
]
graphql-client = [
    "graphql-ktor-client",
    "graphql-client-jackson",
]
metrics = [
    "influxdb-client-kotlin",
    "micrometer-registry-prometheus",
]
logging-runtime = [
    "logback-classic",
    "logstash-logback-encoder",
]
junit = [
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "junit-jupiter-params",
    "kotlin-test-junit5",
]
kotest = [
    "kotest-assertions-core",
    "kotest-assertions-json",
    "kotest-runner-junit5",
]
test = [
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "junit-jupiter-params",
    "kotest-assertions-core",
    "kotest-assertions-json",
    "kotest-runner-junit5",
    "kotlin-test-junit5",
    "kotlinx-coroutines-test",
    "mockk",
]
